import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { HttpModule } from '@angular/http';
// By default, the app generated by ng init will include the FormsModule, here we’re requiring the ReactiveFormsModule as well
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import {AppComponent} from './app';
import {NavModule } from './nav/nav.module';
import {TreeModule} from './tree/tree.module';
import {CustomCommonModule} from './common/c-common.module';
import {CustomPipeModule} from './common/pipes/custom-pipe.module';
import {SampleFormModule} from './samples/forms/sample-form.module';


import {MatchingTagsPipe} from './tagging/pipe/match-tag.pipe';
import {TaggingComponent} from './tagging/tagging.component';
import {TreeRootComponent} from './tree/tree-root.component';
import {TemplateFormComponent} from './samples/forms/template-form.component';

@NgModule({
    imports: [BrowserModule,
        NavModule,
        TreeModule,
        HttpModule,
        FormsModule,
        // Including the ReactiveFormsModule in our application
        ReactiveFormsModule,
        CustomCommonModule,
        CustomPipeModule,
        SampleFormModule,
        RouterModule.forRoot([
            { path: '', redirectTo: 'tagging', pathMatch: 'full' },
            { path: 'tagging', component: TaggingComponent },
            { path: 'tree', component: TreeRootComponent },
            { path: 'templateform', component: TemplateFormComponent},
        ])
    ],
        
    declarations: [AppComponent, TaggingComponent, MatchingTagsPipe ],
    bootstrap: [AppComponent]
})

export class AppModule { }

