import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { HttpModule } from '@angular/http';
// By default, the app generated by ng init will include the FormsModule, here we’re requiring the ReactiveFormsModule as well
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { AppRoutingModule } from './app.routing.module';
import {AppComponent} from './app';
import {NavModule } from './nav/nav.module';
import {TreeModule} from './tree/tree.module';
import {CustomCommonModule} from './common/c-common.module';
import {CustomPipeModule} from './common/pipes/module/custom-pipe.module';
import {SampleFormModule} from './samples/forms/sample-form.module';
import {SharedServiceModule} from './samples/sharedservice/module/shared-service.module';
import {ThirdPartyModule} from './samples/thirdparty/module/thirdparty.module';
import {HttpCallModule} from './samples/httpcall/module/httpcall.module';
import { SearchFilterModule } from './samples/searchfilter/module/searchfilter.module';
import { UserModule } from './user/user.module';


import {MatchingTagsPipe} from './tagging/pipe/match-tag.pipe';
import {TaggingComponent} from './tagging/tagging.component';

@NgModule({
    imports: [BrowserModule,
        UserModule,
        NavModule,
        TreeModule,
        HttpModule,
        FormsModule,
        // Including the ReactiveFormsModule in our application
        ReactiveFormsModule,
        CustomCommonModule,
        CustomPipeModule,
        SharedServiceModule,
        SampleFormModule,
        ThirdPartyModule,
        HttpCallModule,
        SearchFilterModule,
        AppRoutingModule 
    ],
        
    declarations: [AppComponent, TaggingComponent, MatchingTagsPipe ],
    bootstrap: [AppComponent]
})

export class AppModule { }

